### ISSUE TITLE
xmacro4urdf ModuleNotFoundError

### ISSUE THREAD

**Issue by lukebeddow** [gezp/xmacro#1]
Hi, I just installed the latest version of xmacro (v1.2.0) using pip.

When I try to run xmacro I get the following error:

```
Traceback (most recent call last):
  File "/home/luke/.local/bin/xmacro", line 5, in <module>
    from xmacro import xmacro_main
  File "/home/luke/.local/lib/python3.6/site-packages/xmacro/__init__.py", line 3, in <module>
    from xmacro.xmacro4urdf import xmacro4urdf_main
  File "/home/luke/.local/lib/python3.6/site-packages/xmacro/xmacro4urdf.py", line 5, in <module>
    from ament_index_python.packages import get_package_share_directory
ModuleNotFoundError: No module named 'ament_index_python'
```

The issue appears to be with xmacro4urdf, which was added in the new version. I installed the old version (v1.1.2) and I had no issues. I am a ROS user but only with Python2, I suspect this may be the cause of the issue.

Thanks for creating such a great tool! I am fine with the old version now but I wanted to let you know about this issue.

**Comment by gezp** [comment]
Thank you for the feedback, this is a BUG. `ament_index_python` is a ROS2 package which is used by `xmacro4urdf`,  and i'm a ROS2 user so that i didn't find this issue, i will fix this issue as soon as possible.

**Comment by gezp** [comment]
I have fixed this issue, you can try the latest version v1.2.1.

**Comment by lukebeddow** [comment]
Thank you! No issues with the new version
